package linker

import (
	"fmt"
	"strconv"
	"strings"
)

func EmitGo(graph LinkedGraph, plan GenerationPlan) ([]byte, error) {
	if graph.Status != "CLOSED" {
		return nil, fmt.Errorf("Go generation requires CLOSED graph status, got %s", graph.Status)
	}
	if plan.Language != "go" || plan.Package == "" || plan.Entrypoint == "" {
		return nil, fmt.Errorf("invalid Go generation plan")
	}
	var output strings.Builder
	output.WriteString("// Code generated by gooo-module-linker from .gooo metacode; DO NOT EDIT.\n")
	output.WriteString("package " + plan.Package + "\n\n")
	output.WriteString("import \"fmt\"\n\n")
	output.WriteString("type LinkedModule struct {\n\tIdentity string\n\tRelease string\n\tDigest string\n\tCyclePolicy string\n}\n\n")
	output.WriteString("const LinkedSchema = " + strconv.Quote(graph.Schema) + "\n")
	output.WriteString("const LinkedStatus = " + strconv.Quote(graph.Status) + "\n")
	output.WriteString("const LinkedCanonicalDigest = " + strconv.Quote(graph.CanonicalDigest) + "\n\n")
	output.WriteString("var LinkedModules = []LinkedModule{\n")
	for _, module := range graph.Modules {
		output.WriteString("\t{Identity: " + strconv.Quote(module.Identity) + ", Release: " + strconv.Quote(module.Release) + ", Digest: " + strconv.Quote(module.Digest) + ", CyclePolicy: " + strconv.Quote(module.CyclePolicy) + "},\n")
	}
	output.WriteString("}\n\n")
	output.WriteString("func " + plan.Entrypoint + "() {\n")
	output.WriteString("\tfmt.Println(LinkedSchema, LinkedStatus, LinkedCanonicalDigest, len(LinkedModules))\n")
	output.WriteString("}\n")
	return []byte(output.String()), nil
}
