package linker

import (
	"os"
	"path/filepath"
	"strings"
	"testing"
)

func TestThreeModuleGraphIsCanonicalAcrossInputOrder(t *testing.T) {
	policy := mustPolicy(t)
	left := mustModules(t, "fixtures/modules/app.gooo", "fixtures/modules/feature.gooo", "fixtures/modules/core.gooo")
	right := mustModules(t, "fixtures/modules/core.gooo", "fixtures/modules/feature.gooo", "fixtures/modules/app.gooo")
	leftGraph, err := Link(policy, left)
	if err != nil {
		t.Fatal(err)
	}
	rightGraph, err := Link(policy, right)
	if err != nil {
		t.Fatal(err)
	}
	if leftGraph.Status != "CLOSED" || rightGraph.Status != "CLOSED" {
		t.Fatalf("expected CLOSED graphs, got %s and %s", leftGraph.Status, rightGraph.Status)
	}
	if leftGraph.CanonicalDigest != rightGraph.CanonicalDigest {
		t.Fatalf("input order changed canonical digest: %s != %s", leftGraph.CanonicalDigest, rightGraph.CanonicalDigest)
	}
	if len(leftGraph.Modules) != 3 || len(leftGraph.Edges) != 3 {
		t.Fatalf("unexpected graph size: modules=%d edges=%d", len(leftGraph.Modules), len(leftGraph.Edges))
	}
}

func TestUnknownDiagnosticsContainAllSixFields(t *testing.T) {
	policy := mustPolicy(t)
	graph, err := Link(policy, mustModules(t, "fixtures/scenarios/missing-consumer.gooo"))
	if err != nil {
		t.Fatal(err)
	}
	if graph.Status != "UNKNOWN" {
		t.Fatalf("expected UNKNOWN, got %s", graph.Status)
	}
	for _, diagnostic := range graph.Diagnostics {
		if diagnostic.Status != "UNKNOWN" {
			continue
		}
		if diagnostic.Unknown == nil {
			t.Fatal("UNKNOWN diagnostic has no evidence")
		}
		fields := []string{diagnostic.Unknown.Stage, diagnostic.Unknown.Step, diagnostic.Unknown.Reason, diagnostic.Unknown.UnknownClass, diagnostic.Unknown.NextOperation, diagnostic.Unknown.BlockedBy}
		for _, field := range fields {
			if strings.TrimSpace(field) == "" {
				t.Fatalf("UNKNOWN diagnostic has an empty field: %#v", diagnostic.Unknown)
			}
		}
	}
}

func TestCyclePoliciesAreDeclarative(t *testing.T) {
	policy := mustPolicy(t)
	cases := []struct {
		name   string
		status string
		files  []string
	}{
		{name: "refuted", status: "REFUTED", files: []string{"fixtures/scenarios/cycle-a.gooo", "fixtures/scenarios/cycle-b.gooo"}},
		{name: "unknown", status: "UNKNOWN", files: []string{"fixtures/scenarios/cycle-unknown-a.gooo", "fixtures/scenarios/cycle-unknown-b.gooo"}},
		{name: "allow", status: "CLOSED", files: []string{"fixtures/scenarios/cycle-allow-a.gooo", "fixtures/scenarios/cycle-allow-b.gooo"}},
	}
	for _, testCase := range cases {
		t.Run(testCase.name, func(t *testing.T) {
			graph, err := Link(policy, mustModules(t, testCase.files...))
			if err != nil {
				t.Fatal(err)
			}
			if graph.Status != testCase.status {
				t.Fatalf("expected %s, got %s", testCase.status, graph.Status)
			}
		})
	}
}

func TestEmitterUsesAuthoritativeGenerationPlan(t *testing.T) {
	policy := mustPolicy(t)
	graph, err := Link(policy, mustModules(t, "fixtures/modules/core.gooo"))
	if err != nil {
		t.Fatal(err)
	}
	data, err := EmitGo(graph, policy.Generation)
	if err != nil {
		t.Fatal(err)
	}
	text := string(data)
	for _, expected := range []string{"package main", "func main()", graph.CanonicalDigest, "Code generated by gooo-module-linker"} {
		if !strings.Contains(text, expected) {
			t.Fatalf("generated Go is missing %q", expected)
		}
	}
}

func mustPolicy(t *testing.T) Policy {
	t.Helper()
	policy, err := ParsePolicyFile(repoPath("meta/module-linker.gooo"))
	if err != nil {
		t.Fatal(err)
	}
	return policy
}

func mustModules(t *testing.T, paths ...string) []Module {
	t.Helper()
	modules := make([]Module, 0, len(paths))
	for _, path := range paths {
		module, err := ParseModuleFile(repoPath(path))
		if err != nil {
			t.Fatal(err)
		}
		modules = append(modules, module)
	}
	return modules
}

func repoPath(path string) string {
	root, err := os.Getwd()
	if err != nil {
		panic(err)
	}
	return filepath.Join(root, "..", "..", path)
}
